### ISSUE TITLE
tomcat installation fails (failed: [oisserver] => {"dest": "/var/tmp/apache-tomcat-8.0.21.tar.gz", "failed": true...)

### ISSUE THREAD

**Issue by napeits** [ForgeRock/frstack#14]
Solution: edit *ansible/roles/tomcat/defaults/main.yml* and replace **tomcat_version: "8.0.21"** with the current tomcat 8 version (as of today, 8th of June, 2015, it's 8.0.23).
P.S.:
OpenDJ similarly fails to download and likely has a similar fix.
Something should be done to fetch always the latest stable version instead of hardcoding version numbers, maybe in coordination with the implied projects (so that they provide a "latest-stable" link alias, if/when they do not already provide one).

**Comment by wstrange** [comment]
Thanks.

Can you send a pull request with the updated version.

We do need a better strategy for version management.

**Comment by napeits** [comment]
Welcome; just sent a pull req. Regarding OpenDJ, I'm still fighting with it (current nighlty-builds include the date in the filename, while the script doesn't - and the referenced stable version is subscriber-only, which I'm not yet). By the way, is it ok to link to 3.0.0 instead of 2.6.2, or should I expect some hiccups?

**Comment by wstrange** [comment]
I can't see the pull request.  Can you check again?

I think 3.0.0 is OK - but one or two command line options may have changed - so the install role for opendj may have to be modified.

**Comment by napeits** [comment]
I have just merged it; can you see it now? I've applied the "fork+pull model" as per https://help.github.com/articles/using-pull-requests/, which resulted in the creation of https://github.com/napeits/frstack/pull/1 - I guess this is the expected way to proceed in the case of your project, as I'm not directly part of it - but it could be that I missed something in the process, that doesn't let you automatically see my pull request... 

Ok, thanks, I'll try again when I catch time.

**Comment by wstrange** [comment]
I'm still not seeing any pull request. 

I think you need to bring up your fork (on github page). There should be a way to submit the pull request upstream to the fork

**Comment by napeits** [comment]
And now? Regarding OpenDJ, finally tried it again, in effect there's an option regarding self-signed ssl certs to add, else install fails. Plus if the latest nightly is from yesterday, going back in time on both the host and guest machines (the latter, via "vagrant ssh") reconciliates virtual reality with the script, which expects the nightly to be from no earlier than today (or hard-code everything again, since the commit hour cannot be guessed). Now encountering the same issue with OpenAM because of that very trick - time to get back (or forward, to be exact) to real-world time! By the way, since this involves weird trickery with system time, I am unable to provide a patch for this one (excepted the backwards, hard-coded way). Definitely, something like a latest-stable (or latest-nightly) link for all building blocks (at least forgerock's) would help quite a bit to sort this out elegantly, without having to resort to setting unreal times and such.

**Comment by napeits** [comment]
P.S.: on line 20 of ansible/roles/opendj/tasks/main.yml, add "  --generateSelfSignedCertificate" (without the quotes, with the space) at the end of the line when/if installing OpenDJ 3.0.0 nightly. Still involves the aforementioned trickery / hard-coding of the installation file to download, so not submitting as a patch yet.

**Comment by wstrange** [comment]
I have gone back to a simpler strategy of separating the download from the ansible install. See vagrant/getnightly.sh

This should resolve some of the version issues
